### ISSUE TITLE
linstor_un not working with Ubuntu 20.04

### ISSUE THREAD

**Issue by marcusaram** [OpenNebula/addon-linstor_un#10]
Hi,

I was trying to run linstor_un on Ubuntu 20.04, setup everything was fine. But when trying to put an image on the image store it fails every time. After some debugging I found out what it was. qemu-img has changed a little bit its output.

It fails by determining the image size with qemu-img.

Ubuntu uses qemu-img version `qemu-img version 4.2.0 (Debian 1:4.2-3ubuntu6.1)`, don't known when it was changed.

```
in datastore/linstor_un/cp

ORIGINAL_SIZE_B="$($SSH $DST_HOST $QEMU_IMG info $TMP_DST | $AWK -F'[ ()]+' '/^virtual size: / {print $4}')"

should be

ORIGINAL_SIZE_B="$($SSH $DST_HOST $QEMU_IMG info $TMP_DST | $AWK -F'[ ()]+' '/^virtual size: / {print $5}')"
```

**Comment by kvaps** [comment]
Thanks for the report, I can reproduce:
```bash
# wget https://s3-eu-west-1.amazonaws.com/opennebula-marketplace/ubuntu2004min-5.11.80-1.20200506.qcow2

# qemu-img --version
qemu-img version 4.2.0 (Debian 1:4.2-3ubuntu6.1)
Copyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers

# qemu-img info ubuntu2004min-5.11.80-1.20200506.qcow2
image: ubuntu2004min-5.11.80-1.20200506.qcow2
file format: qcow2
virtual size: 2.2 GiB (2361393152 bytes)
disk size: 194 MiB
cluster_size: 65536
Format specific information:
    compat: 1.1
    lazy refcounts: false
    refcount bits: 16
    corrupt: false
```

problem fixed in https://github.com/OpenNebula/addon-linstor_un/commit/96dacdb9faef3e0c142bc7c03e4588416e461ae8
