### ISSUE TITLE
Run thaw hook even after failed domfsfreeze?

### ISSUE THREAD

**Issue by chiraganand** [OpenNebula/addon-linstor_un#11]
https://github.com/OpenNebula/addon-linstor_un/blob/616fae7b40537dafc131043e81f427e006f32e50/tm/linstor_un/snap_create_live#L100-L103

The if condition in the above code creates a trap _only if_ fsfreeze was successful. In case, there are fsfreeze hooks implemented on the guest (`/etc/qemu-ga/fsfreeze.d/`) then these hook scripts may need to run again with `thaw` parameter so that they can clean up properly (free up locks, etc.).

Case in point: database locks. One can create database locks before creating a disk snapshot. The lock remains till the filesystem is frozen and will have to be freed after fs is unfrozen. If fsfreeze fails but the hook has run then db lock won't be freed until the script is run again with `thaw` parameter.

Removing the `if` condition from the above code might solve this. `domfsthaw` doesn't throw an error if one tries to thaw an unfrozen fs of a guest.

**Comment by kvaps** [comment]
Hi, thanks for the report!

I think we should put this issue up to discussion, do we really need to call `domfsfreeze` and `domfsthaw` at all, LINSTOR runs `drbdadm suspend-io/resume-io` by itself every time before creating an snapshot.

What do you think, is there any reasons why to leave this?

**Comment by chiraganand** [comment]
> Hi, thanks for the report!
> 
> I think we should put this issue up to discussion, do we really need to call `domfsfreeze` and `domfsthaw` at all, LINSTOR runs `drbdadm suspend-io/resume-io` by itself every time before creating an snapshot.
> 
> What do you think, is there any reasons why to leave this?

From FSFREEZE(8):
>        fsfreeze  halts  any  new  access to the filesystem and creates a stable image on disk.  fsfreeze is intended to be used
>        with hardware RAID devices that support the creation of snapshots.
> 
>        fsfreeze is unnecessary for device-mapper devices.  The device-mapper (and LVM) automatically freezes  a  filesystem  on
>        the device when a snapshot creation is requested.  For more details see the dmsetup(8) man page.

The problem in OpenNebula case is that volumes are really _disk images_ and not partitions with filesystems. In this case, LVM, for example, does not recognise the filesystem because the first partition of this volume which has the filesystem really begins after 2048 bytes (as seen on our boxes, see example disk structure below) and cannot freeze the filesystem on its own. LVM works on device mapper framework and issues `dmsetup suspend` on the device which attempts to sync the filesystem if there is one found on the device (unless --nolockfs is used) and flushes any IO to disk (unless --noflush is used) before suspending the device (REF: DMSETUP(8)).

I am not sure how DRBD does suspend-io/resume-io works but I am guessing it stops any further incoming requests on the device ([slight mention of this here](https://patchwork.kernel.org/patch/10739149/)) but doesn't work at filesystem level. `fsfreeze`, on the other hand, freezes the filesystem and "creates a stable image" on disk as mentioned in their man page.

Example disk structure:
```
# fdisk -l disk-0.img  | grep -A1 Start
     Device Boot      Start         End      Blocks   Id  System
disk-0.img1   *        2048   104859662    52428807+  83  Linux
```

**Comment by kvaps** [comment]
Thanks for your research.

> I am not sure how DRBD does suspend-io/resume-io works but I am guessing it stops any further incoming requests on the device.

Exactly, at `suspend-io` they are just stop, like with broken iSCSI drive, until `resume-io` operation.

> VM works on device mapper framework and issues dmsetup suspend on the device which attempts to sync the filesystem if there is one found on the device (unless --nolockfs is used) and flushes any IO to disk (unless --noflush is used) before suspending the device (REF: DMSETUP(8)).

But this makes no sense if filesystem mounted inside the VM, in this way the host knows nothing about entry of block device. Isn't it?

**Comment by chiraganand** [comment]
> > LVM works on device mapper framework and issues dmsetup suspend on the device which attempts to sync the filesystem if there is one found on the device (unless --nolockfs is used) and flushes any IO to disk (unless --noflush is used) before suspending the device (REF: DMSETUP(8)).
> 
> But this makes no sense if filesystem mounted inside the VM, in this way the host knows nothing about entry of block device. Isn't it?

Sorry, do you mean the VM does not get to know if the buffers are being flushed to disk by the host?

**Comment by kvaps** [comment]
I'm just saying that host have no access to guest fs, so I guess it can't initiate the sync for the guest filesystem anyway.

**Comment by chiraganand** [comment]
> I'm just saying that host have no access to guest fs, so I guess it can't initiate the sync for the guest filesystem anyway.

Well, it really depends. By the looks of it if the guest FS exists on a device which itself is created on the host as a mapped device (eg. LVM) then device mapper utilities on the host can really sync this filesystem and freeze it (according to dmsetup(8)).

**Comment by kvaps** [comment]
OK, @vitalif is also pointed to man pages about fsfreeze:

```
man fsfreeze
-f, --freeze
    This option requests the specified a filesystem to be frozen from new modifications. When this is selected, all ongoing transactions in the filesystem are allowed to complete, new write system calls are halted, other calls which modify the filesystem are halted, and all dirty data, metadata, and log information are written to disk. Any process attempting to write to the frozen filesystem will block waiting for the filesystem to be unfrozen.
```

So probably, it is making some sense, I'll leave `domfsfreeze` and `domfsthaw` in code and implement the changes which you requested.

**Comment by kvaps** [comment]
fixed in https://github.com/OpenNebula/addon-linstor_un/commit/5d2e656034e2ce9382efdaa96b1712e3507284cf, thank you for cooperation

**Comment by chiraganand** [comment]
> So probably, it is making some sense, I'll leave `domfsfreeze` and `domfsthaw` in code and implement the changes which you requested.

Great. Thanks for the fix, and, of course, the very useful driver.
