### ISSUE TITLE
Cannot delete VM with snapshots

### ISSUE THREAD

**Issue by chiraganand** [OpenNebula/addon-linstor_un#14]
While executing delete command on a resource all the snapshots belonging to the resource are not deleted, hence, Linstor refuses to delete the resource.

```
Command execution failed (exit code: 1): /var/lib/one/remotes/tm/linstor_un/delete HOST-1:/var/lib/one//datastores/111/2370/disk.0 2370 112
...
Command "linstor resource-definition delete one-vm-2370-disk-0" failed: Cannot delete resource definition '\''one-vm-2370-disk-0'\'' because it has snapshots.
```

I dug down that this problem is probably happening because of LINBIT/linstor-client#41. The following function is not returning any output:
https://github.com/OpenNebula/addon-linstor_un/blob/5d2e656034e2ce9382efdaa96b1712e3507284cf/datastore/linstor_un/linstor_utils.sh#L188-L193

This is not really a `linstor_un` issue but I am reporting it because we might use a workaround to this problem until the actual bug is fixed.

**Comment by chiraganand** [comment]
This is solved. Workaround for earlier versions (< v1.7.0) of Linstor server is to change `linstor_get_snap_names_for_res` function in `linstor_utils.sh`:
```
function linstor_get_snap_names_for_res {
    local RES="$1"
    $LINSTOR -m --output-version v0 snapshot list | \
        $JQ -r ".[].snapshot_dfns[]? | select(.rsc_name == \"$RES\") | .snapshot_name" | \
        xargs
}
```

**Comment by chiraganand** [comment]
> This is solved. Workaround for earlier versions (< v1.7.0) of Linstor server is to change `linstor_get_snap_names_for_res` function in `linstor_utils.sh`:
> 
> ```
> function linstor_get_snap_names_for_res {
>     local RES="$1"
>     $LINSTOR -m --output-version v0 snapshot list | \
>         $JQ -r ".[].snapshot_dfns[]? | select(.rsc_name == \"$RES\") | .snapshot_name" | \
>         xargs
> }
> ```

`xargs` at the end of statement is removing end-of-line `\n` characters, hence, `linstor_get_snap_ids_for_res` is not working correctly.

**Comment by kvaps** [comment]
Thanks for the report, fixed in https://github.com/OpenNebula/addon-linstor_un/commit/b7a45dba72e8609eedf968986631c9d6e622b3da
