### ISSUE TITLE
Image Datastore does not support transfer mode: linstor_un

### ISSUE THREAD

**Issue by quiknick** [OpenNebula/addon-linstor_un#17]
I am able to use the image datastore and add new disk images to use, but instantiating an image using the system datastore fails. I have tried several changes to the config to no avail.  Linstor storage is working properly.   All configurations following the blog and git README.md are set properly and have proven that images datastore works fine. systems datastore not working.

$ tail /var/log/one/sched.log
Tue Feb  8 09:33:58 2022 [Z0][VM][D]: Found 1 pending/rescheduling VMs.
Tue Feb  8 09:33:58 2022 [Z0][HOST][D]: Discovered 1 enabled hosts.
Tue Feb  8 09:33:58 2022 [Z0][VM][D]: VMs in VMGroups:

Tue Feb  8 09:33:58 2022 [Z0][VNET][D]: Discovered 1 vnets.
Tue Feb  8 09:33:58 2022 [Z0][VM][E]: Error deploying virtual machine 7 to HID: 0. Reason: [one.vm.deploy] Image Datastore does not support transfer mode: linstor_un
Tue Feb  8 09:33:58 2022 [Z0][SCHED][D]: Dispatching VMs to hosts:

system-ds.conf
NAME="linstor-system"
TYPE="SYSTEM_DS"
LS_CONTROLLERS="x.x.x.x"
RESOURCE_GROUP="opennebula"
STORAGE_POOL="LinstorData"
AUTO_PLACE="2"
CLONE_MODE="snapshot"
CHECKPOINT_AUTO_PLACE="1"
TM_MAD="linstor_un"
PREFER_NODE="yes"

tried CLONE_MODE copy and snapshot

addon-linstor_un git (1.8.2)
Opennebula 6.2.0
drbd-dkms 9.1.5
drbd-utils 9.20.2
linstor-client 1.12.0
linstor-common 1.17.0
linstor-controller 5.2.2
linstor-satellite 1.17.0
python-linstor 1.12.0
thin-send-recv 1.0-1

**Comment by kvaps** [comment]
Hi, please double check your `DATASTORE_MAD`, it should have `linstor_un` two times

```diff
 DATASTORE_MAD = [
     EXECUTABLE = "one_datastore",
-    ARGUMENTS  = "-t 15 -d dummy,fs,lvm,ceph,dev,iscsi_libvirt,vcenter -s shared,ssh,ceph,fs_lvm,qcow2,vcenter"
+    ARGUMENTS  = "-t 15 -d dummy,fs,lvm,ceph,dev,iscsi_libvirt,vcenter,linstor_un -s shared,ssh,ceph,fs_lvm,qcow2,vcenter,linstor_un"
 ]
```

**Comment by quiknick** [comment]
Thanks for super-fast response. Yes, I had that properly configured twice. I just redeployed. it is working now.
