### ISSUE TITLE
datastore/linstor_un/snap_revert: typo in line 103

### ISSUE THREAD

**Issue by AndrewV666** [OpenNebula/addon-linstor_un#9]
https://github.com/OpenNebula/addon-linstor_un/blob/a9068448cd9bb808a965e8aa5338dd58944a22cb/datastore/linstor_un/snap_revert#L103

extra "; then" in line 103.

**Comment by kvaps** [comment]
Thanks for bug report!
I'm going to update snapshots management today

**Comment by AndrewV666** [comment]
Looking forward for it, thank you!

**Comment by kvaps** [comment]
Okay, new release `v1.4.1` includes better snapshot management.
